repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: CHANGELOG.md
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    -   id: check-yaml
        exclude: CHANGELOG.md
    -   id: check-added-large-files
        exclude: CHANGELOG.md

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade


default_language_version:
  python: python3.9
