name: Add contributors
on: [push, pull_request]

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'mmattDonk/AI-TTS-Donations'
        CONTRIBUTOR: "### ðŸ™Œ Code Contributors"
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'chore(docs/README): Updated contributors'
        AVATAR_SHAPE: 'round'
        IGNORED_CONTRIBUTORS: 'mmattisinschool'
